---
title: "Quantitative Reproducibility"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Loading Packages 

```{r load-packages, message = FALSE, warning=FALSE, echo = FALSE}

library(ggplot2)
library(dplyr)
library(statsr)
library(GGally)
library(gridExtra)
library(tidyverse)
library(pander)
library(forcats)
library(tableone)
options(width = 135)
```

##Loading and Cleaning Data

```{r}

#Data was collected in two separate excel sheets. We need to load them and merge them. 

Repro1 <- readxl::read_excel("/Users/mona/Desktop/Research/QuantRepro/ForAnalysis.xlsx")
Repro2 <- readxl::read_excel("/Users/mona/Desktop/Research/QuantRepro/ForAnalysisPart2copy.xlsx")

Repro <- merge(Repro1, Repro2, all = T)

Repro <- Repro[order(Repro$ID),]
  
#Since two coders reviewed the data, this is the data set with all reconciled information. Therefore there are two rows for each data entry (one for each coder). This eliminates the duplicate entries. We should have 400 leftover.
Repro <- Repro %>% filter(Coder == "LK") 

#Re-numbers the rows.
Repro <- Repro %>% replace("ID", 1:400)

#Cleaning the MetaAnalysis variable

as.character(Repro$MetaAnalysis)

Repro$MetaAnalysis[Repro$MetaAnalysis =="0"] <- "None"

Repro$MetaAnalysis[Repro$MetaAnalysis =="1"] <- "A single citation"

Repro$MetaAnalysis[Repro$MetaAnalysis <= "5" & Repro$MetaAnalysis >="2"] <- "Two to five citations"

Repro$MetaAnalysis[Repro$MetaAnalysis =="NA"] <- NA

levels(Repro$MetaAnalysis) <- c("None", "A single citation", "Two to five citations")

#Cleaning the Systematic Review variable

as.character(Repro$Systematic)

Repro$Systematic[Repro$Systematic =="0"] <- "None"

Repro$Systematic[Repro$Systematic =="1"] <- "A single citation"

Repro$Systematic[Repro$Systematic>="2" & Repro$Systematic<="5"] <- "Two to five citations"

Repro$Systematic[Repro$Systematic =="NA"] <- NA

levels(Repro$Systematic) <- c("None", "A single citation", "Two to five citations")


#Cleaning the Replication variable

as.character(Repro$Replication)

Repro$Replication[Repro$Replication =="0"] <- "None"

Repro$Replication[Repro$Replication =="1"] <- "A single citation"

Repro$Replication[Repro$Replication>="2" & Repro$Systematic<="5"] <- "Two to five citations"

Repro$Replication[Repro$Replication =="NA"] <- NA

levels(Repro$Replication) <- c("None", "A single citation", "Two to five citations")

```

## Creating a subset of Empirical data 

```{r}

#Exclude the texts that we could not access online (n = 3).
Repro <- Repro %>% filter(Issues == "There are no issues") 

#Number of studies with no empirical data.
sum(Repro$StudyType == "No empirical data (e.g. editorials, commentaries [without reanalysis], simulations, news, and reviews) -- skip to question 36")

#Exclude non-empirical studies (n = 113). This should give us 284 studies. 
ReproEmpirical <- Repro  %>% filter(Repro$StudyType != "No empirical data (e.g. editorials, commentaries [without reanalysis], simulations, news, and reviews) -- skip to question 36") 

#Number of studies that are case studies
sum(ReproEmpirical$StudyType == "Empirical data: case study")

#Number of studies that are case studies
sum(ReproEmpirical$StudyType == "Empirical data: case series")

#Exclude case reports and case series (n = 81). This should give us 203 studies. 
ReproEmpirical <- ReproEmpirical  %>% filter(ReproEmpirical$StudyType != "Empirical data: case study")
ReproEmpirical <- ReproEmpirical  %>% filter(ReproEmpirical$StudyType != "Empirical data: case series")
```

#Creating Table: List of Journal Names

```{r}

#List of Journals Included

levels(as.factor(Repro$Journal))

#List of Journal Impact Factors

table(Repro$Journal, Repro$Impact)

#Number of articles from each Journal

count(Repro$Journal)


```


#Creating Table: Study Characteristics

```{r set-options, echo=FALSE, cache=FALSE, fig.width=1000, fig.height=1000}
options(width = 10000)

#Creating the Table

row_variables <- 
  c("Journal", 
    "StudyType", 
    "Country", 
    "Subjects",
    "MetaAnalysis",
    "Systematic")
options(width = 4000)
characteristics <- print(
                  CreateTableOne(vars = row_variables, 
                        data = Repro, 
                        includeNA = FALSE), 
                        showAllLevels = TRUE,
                        width = 1000)

#Replication Studies for only studies that had empirical data

characteristics1 <- print(
                  CreateTableOne(vars = "Replication", 
                        data = ReproEmpirical, 
                        includeNA = T), 
                        showAllLevels = TRUE)

table(ReproEmpirical$Replication)
  

```

#Creating Table: Reproducible Characteristics


```{r pressure, echo=FALSE}

#Looking at all studies

repro_variables <- 
  c("Open", 
    "Funding", 
    "COI")

characteristics2 <- print(
                  CreateTableOne(vars = repro_variables, 
                        data = Repro, 
                        includeNA = FALSE), 
                        showAllLevels = TRUE)

#Only studies that had empirical data.

repro_variables1 <- 
  c("Data", 
    "Register", 
    "Protocol", 
    "Script",
    "Materials")

characteristics3 <- print(
                  CreateTableOne(vars = repro_variables1, 
                        data = ReproEmpirical, 
                        includeNA = FALSE), 
                        showAllLevels = TRUE)

#Confidence Intervals  

#Open Access

#monastest <- function(x,y){binom.test(x, y, 0.5, alternative = "two-sided", conf.level = 0.95)}

#sapply(monastest())

binom.test(352, 397,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

binom.test(45, 397,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

#Funding

binom.test(204, 397,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

binom.test(118, 397,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

binom.test(43, 397,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

binom.test(25, 397,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

binom.test(6, 397,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

binom.test(1, 397,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

#COI Statement

binom.test(329, 397,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

binom.test(35, 397,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

binom.test(32, 397,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

binom.test(1, 397,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

#Data availability

binom.test(197, 203,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

binom.test(5, 203,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

binom.test(1, 203,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

#Pre-registration

binom.test(199, 203,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

binom.test(4, 203,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

#Protocol

binom.test(196, 203,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

binom.test(7, 203,
           0.5,
           alternative="two.sided",
           conf.level=0.95)


#Material availability

binom.test(186, 203,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

binom.test(17, 203,
           0.5,
           alternative="two.sided",
           conf.level=0.95)

```

#Miscellaneous 
```{r}

#Among publications that were publicly funded, which ones were available via open access? 

FundOpen <- Repro %>% filter(Repro$Funding == "Yes - the statement says that there was funding from a public organization" & Repro$Open == "Yes - found via Open Access Button")

summary(FundOpen)

```

```{r}
#We would like to do a sub-group comparison based on journal type.

#Create a new variable that creates the following subgroups:

#Aesthetics
#-Aesthetic plastic surgery
#-Aesthetic surgery journal
#-Facial plastic surgery
#-Facial plastic surgery clinics NA
#-JAMA facial plastics

#CMF
#-Journal of CMF
#-Journal of craniofacial surgery

#General
#-Annals plastic surgery
#-Clinics in plastic surgery
#-Journal of plastic surgery and hand surgery
#-Journal of reconstructive microsurgery
#-JPRAS 

#Plastic and Reconstructive Surgery will stand alone as a variable called PRS 

#Creating the new variable, called JournalType

Repro$JournalType <- as.factor(Repro$Journal)

levels(Repro$JournalType) <- list(Aesthetics=c("Aesthetic plastic surgery",
                                               "Aesthetic surgery journal",
                                               "Facial plastic surgery",
                                               "Facial plastic surgery clinics of north america",
                                               "JAMA facial plastic surgery"),
                                  CMF=c("Journal of cranio-maxillo-facial surgery",
                                        "Journal of Craniofacial surgery"),
                                  General=c("Ann Plast Surg",
                                            "Clinics in plastic surgery",
                                            "Journal of Plastic Reconstructive and Aesthetic Surgery",
                                            "Journal of plastic surgery and hand surgery",
                                            "Journal of reconstructive microsurgery"),
                                  PRS="Plastic and reconstructive surgery")

#Let's see if we have equal numbers in each group so we can do a reasonable comparison.

count(Repro$JournalType)

#Looks good. Let's do a Fisher's test, since we have two categorical variables with small counts. We will examine the following variables: citation in a systematic review, citation in a meta-analysis, open access status, funding, COI statement, data availability, pre-registration, protocol, material availablity, and whether they are dependent on Journal Type (aesthetic, CMF, PRS, General) 


ReproEmpirical$JournalType <- as.factor(ReproEmpirical$Journal)

levels(ReproEmpirical$JournalType) <- list(Aesthetics=c("Aesthetic plastic surgery",
                                               "Aesthetic surgery journal",
                                               "Facial plastic surgery",
                                               "Facial plastic surgery clinics of north america",
                                               "JAMA facial plastic surgery"),
                                  CMF=c("Journal of cranio-maxillo-facial surgery",
                                        "Journal of Craniofacial surgery"),
                                  General=c("Ann Plast Surg",
                                            "Clinics in plastic surgery",
                                            "Journal of Plastic Reconstructive and Aesthetic Surgery",
                                            "Journal of plastic surgery and hand surgery",
                                            "Journal of reconstructive microsurgery"),
                                  PRS="Plastic and reconstructive surgery")

#Plots and Fisher Exact Test 

##Reproducible Factors we'd like to examine: Open access (Repro), Funding (Repro), COI statemnet (Repro), Data availability (Empirical), Pre-registration (Empirical), Protocol access (Empirical), Analysis scripts (Empirical), material availability (Empirical) 

## theme(axis.text.x = element_text(angle = 45, hjust = 1)) <- can use this in case you need to angle the text 

##Open Access - ALL DATA

#ggplot(Repro, aes(Open, fill = JournalType)) + geom_bar(position = "dodge") + labs(title="Open Access Status by Journal Type", y = "Count", x = "Available via Open Access") + geom_text(stat="count", aes(label = ..count..), position=position_dodge(width=0.9), vjust=-0.25) + scale_x_discrete(labels = c("No", "Yes")) + labs(fill = "Journal Type") 

ggplot(Repro, aes(JournalType, fill = Open)) + geom_bar(position = "dodge") + labs(title="Open Access Status by Journal Type", y = "Count", x = "Journal Type") + geom_text(stat="count", aes(label = ..count..), position=position_dodge(width=0.9), vjust=-0.25) + scale_fill_discrete(name = "Open Access", labels = c("No", "Yes")) + guides(fill = guide_legend(reverse=TRUE)) + annotate("text", x=1, y=-5, label= "38.6%") + annotate("text", x = 2, y=-5, label = "3.6%") + annotate("text", x = 3, y=-5, label = "6.2%") + annotate("text", x = 4, y=-5, label = "7.5%")

fisher.test(Repro$JournalType, Repro$Open, or = 1, alternative = "two.sided", conf.int = TRUE, conf.level = 0.95)

##Funding Statement - ALL DATA 
##In order to create a plot that is easy to understand, and to facilitate Fisher's Exact Test, we will binarize the funding variable.

##Replicate the funding variable so we can manipulate it.
Repro$Funding1 <- Repro$Funding
Repro$Funding1 <- as.factor(Repro$Funding1)
levels(Repro$Funding1)
levels(Repro$Funding1)[1] <-  "Yes"
levels(Repro$Funding1)[2] <-  "No"
levels(Repro$Funding1)[3:6] <-  "Yes"
Repro$Funding1 <- relevel(Repro$Funding1, "No")

##Funding plot and Fisher's test 
ggplot(Repro, aes(Funding1, fill = JournalType)) + geom_bar(position = "dodge") + labs(title="Funding Statement Availability by Journal Type", y = "Count", x = "Funding Statement Availability") + geom_text(stat="count", aes(label = ..count..), position=position_dodge(width=0.9), vjust=-0.25) + labs(fill = "Journal Type") +  scale_x_discrete(limits=c("No", "Yes"))

ggplot(Repro, aes(JournalType, fill = Funding1)) + geom_bar(position = "dodge") + labs(title="Funding Statement Availability by Journal Type", y = "Count", x = "Journal Type") + geom_text(stat="count", aes(label = ..count..), position=position_dodge(width=0.9), vjust=-0.25) +  scale_fill_discrete(name = "Funding", labels = c("No", "Yes")) + guides(fill = guide_legend(reverse=TRUE)) + annotate("text", x=1, y=-5, label= "55.7%") + annotate("text", x = 2, y=-5, label = "32.8%") + annotate("text", x = 3, y=-5, label = "76.3%") + annotate("text", x = 4, y=-5, label = "37.6%")

fisher.test(Repro$JournalType, Repro$Funding1, or = 1, alternative = "two.sided", conf.int = TRUE, conf.level = 0.95)

##COI Statement - ALL DATA

##In order to create a plot that is easy to understand, and to facilitate Fisher's Exact Test, we will binarize the COI variable.

##Replicate the COI variable so we can manipulate it.
Repro$COI1 <- Repro$COI
Repro$COI1 <- as.factor(Repro$COI1)
levels(Repro$COI1)
levels(Repro$COI1)[1] <-  "Yes"
levels(Repro$COI1)[2] <-  "No"
levels(Repro$COI1)[3:4] <-  "Yes"
Repro$COI1 <- relevel(Repro$COI1, "No")

#ggplot(Repro, aes(COI1, fill = JournalType)) + geom_bar(position = "dodge") + labs(title="Conflict of Interest Statement by Journal Type", y = "Count", x = "Conflict of Interest Statement") + geom_text(stat="count", aes(label = ..count..), position=position_dodge(width=0.9), vjust=-0.25) + labs(fill = "Journal Type") +  scale_x_discrete(limits=c("No", "Yes"))

ggplot(Repro, aes(JournalType, fill = COI1)) + geom_bar(position = "dodge") + labs(title="Conflict of Interest Statement by Journal Type", y = "Count", x = "Journal Type") + geom_text(stat="count", aes(label = ..count..), position=position_dodge(width=0.9), vjust=-0.25) + labs(fill = "COI") + annotate("text", x=1, y=-5, label= "11.4%") + annotate("text", x = 2, y=-5, label = "11.7%") + annotate("text", x = 3, y=-5, label = "8.2%") + annotate("text", x = 4, y=-5, label = "3.2%") + guides(fill = guide_legend(reverse=TRUE))  

fisher.test(Repro$JournalType, Repro$COI1, or = 1, alternative = "two.sided", conf.int = TRUE, conf.level = 0.95)

##Protocol Availability - Empirical Data Only
#ggplot(ReproEmpirical, aes(Protocol, fill = JournalType)) + geom_bar(position = "dodge") + labs(title="Protocol Availability by Journal Type", y = "Count", x = "Protocol Availability") + geom_text(stat="count", aes(label = ..count..), position=position_dodge(width=0.9), vjust=-0.25) + scale_x_discrete(labels = c("No", "Yes")) + labs(fill = "Journal Type")

ggplot(ReproEmpirical, aes(JournalType, fill = Protocol)) + geom_bar(position = "dodge") + labs(title="Protocol Availability by Journal Type", y = "Count", x = "Journal Type") + geom_text(stat="count", aes(label = ..count..), position=position_dodge(width=0.9), vjust=-0.25) + scale_fill_discrete(name = "Protocol", labels = c("No", "Yes")) + guides(fill = guide_legend(reverse=TRUE)) + annotate("text", x=1, y=-5, label= "11.4%") + annotate("text", x = 2, y=-5, label = "1.4%") + annotate("text", x = 3, y=-5, label = "3.4%") + annotate("text", x = 4, y=-5, label = "0.0%")

fisher.test(ReproEmpirical$JournalType, ReproEmpirical$Protocol, or = 1, alternative = "two.sided", conf.int = TRUE, conf.level = 0.95)

##Material Availability - Empirical Data Only 
#ggplot(ReproEmpirical, aes(Materials, fill = JournalType)) + geom_bar(position = "dodge")  + labs(title="Study Material Availability by Journal Type", y = "Count", x = "Study Material Availability") + geom_text(stat="count", aes(label = ..count..), position=position_dodge(width=0.9), vjust=-0.25) + scale_x_discrete(labels = c("No", "Yes")) + labs(fill = "Journal Type")

ggplot(ReproEmpirical, aes(JournalType, fill = Materials)) + geom_bar(position = "dodge")  + labs(title="Study Material Availability by Journal Type", y = "Count", x = "Journal Type") + geom_text(stat="count", aes(label = ..count..), position=position_dodge(width=0.9), vjust=-0.25) + scale_fill_discrete(name = "Materials", labels = c("No", "Yes")) + guides(fill = guide_legend(reverse=TRUE)) + annotate("text", x=1, y=-5, label= "20.0%") + annotate("text", x = 2, y=-5, label = "4.3%") + annotate("text", x = 3, y=-5, label = "3.4%") + annotate("text", x = 4, y=-5, label = "12.5%")

fisher.test(ReproEmpirical$JournalType, ReproEmpirical$Materials, or = 1, alternative = "two.sided", conf.int = TRUE, conf.level = 0.95)

##Data Availability
ReproEmpirical$Data1 <- ReproEmpirical$Data
ReproEmpirical$Data1 <- as.factor(ReproEmpirical$Data1)
levels(ReproEmpirical$Data1)
levels(ReproEmpirical$Data1)[1:2] <-  "No"
levels(ReproEmpirical$Data1)[2] <-  "Yes"

#ggplot(ReproEmpirical, aes(Data1, fill = JournalType)) + geom_bar(position = "dodge") + labs(title="Data Availability Statement by Journal Type", y = "Count", x = "Data Availability Statement") + geom_text(stat="count", aes(label = ..count..), position=position_dodge(width=0.9), vjust=-0.25) + labs(fill = "Journal Type") +  scale_x_discrete(limits=c("No", "Yes"))

ggplot(ReproEmpirical, aes(JournalType, fill = Data1)) + geom_bar(position = "dodge") + labs(title="Data Availability Statement by Journal Type", y = "Count", x = "Journal Type") + geom_text(stat="count", aes(label = ..count..), position=position_dodge(width=0.9), vjust=-0.25) + scale_fill_discrete(name = "Data", labels = c("No", "Yes")) + guides(fill = guide_legend(reverse=TRUE)) + annotate("text", x=1, y=-5, label= "2.9%") + annotate("text", x = 2, y=-5, label = "5.7%") + annotate("text", x = 3, y=-5, label = "0.0%") + annotate("text", x = 4, y=-5, label = "0.0%")

fisher.test(ReproEmpirical$JournalType, ReproEmpirical$Data1, or = 1, alternative = "two.sided", conf.int = TRUE, conf.level = 0.95)

##Pre Registration -- we will only make a plot, we  will not perform Fisher's test given the small number of observations. Empirical Data only.

ggplot(ReproEmpirical, aes(Register, fill = JournalType)) + geom_bar(position = "dodge")  + labs(title="Pre-Registration Statement by Journal Type", y = "Count", x = "Pre-Registration Statement") + geom_text(stat="count", aes(label = ..count..), position=position_dodge(width=0.9), vjust=-0.25) + scale_x_discrete(labels = c("No", "Yes")) + labs(fill = "Journal Type")

##Given that no studies provided analysis scripts, we will not analyze this variable with a plot or with Fisher's exact test.


```


